# Generated by Django 2.2.13 on 2021-04-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210413_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='NO IMAGE', upload_to=''),
            preserve_default=False,
        ),
    ]
