# Generated by Django 2.2.13 on 2021-04-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210413_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='No Image', upload_to=''),
            preserve_default=False,
        ),
    ]
