# Generated by Django 2.2.13 on 2021-04-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210413_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='files',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
